### YamlMime:ManagedReference
items:
- uid: com.absence.variablebanks.editor.PackageSettings.AssetManagementConstants
  commentId: T:com.absence.variablebanks.editor.PackageSettings.AssetManagementConstants
  id: PackageSettings.AssetManagementConstants
  parent: com.absence.variablebanks.editor
  children:
  - com.absence.variablebanks.editor.PackageSettings.AssetManagementConstants.K_ADDRESSABLES_INDEX
  - com.absence.variablebanks.editor.PackageSettings.AssetManagementConstants.K_RESOURCES_INDEX
  langs:
  - csharp
  - vb
  name: PackageSettings.AssetManagementConstants
  nameWithType: PackageSettings.AssetManagementConstants
  fullName: com.absence.variablebanks.editor.PackageSettings.AssetManagementConstants
  type: Class
  source:
    remote:
      path: absent-variablebanks/Assets/Plugins/absencee_/absent-variablebanks/Editor/Initial/PackageSettings.cs
      branch: development
      repo: https://github.com/b1lodHand/absent-variablebanks.git
    id: AssetManagementConstants
    path: ../absent-variablebanks/Assets/Plugins/absencee_/absent-variablebanks/Editor/Initial/PackageSettings.cs
    startLine: 14
  assemblies:
  - Assembly-CSharp-Editor-firstpass
  namespace: com.absence.variablebanks.editor
  summary: Constants for asset management.
  example: []
  syntax:
    content: public static class PackageSettings.AssetManagementConstants
    content.vb: Public Module PackageSettings.AssetManagementConstants
  inheritance:
  - System.Object
- uid: com.absence.variablebanks.editor.PackageSettings.AssetManagementConstants.K_RESOURCES_INDEX
  commentId: F:com.absence.variablebanks.editor.PackageSettings.AssetManagementConstants.K_RESOURCES_INDEX
  id: K_RESOURCES_INDEX
  parent: com.absence.variablebanks.editor.PackageSettings.AssetManagementConstants
  langs:
  - csharp
  - vb
  name: K_RESOURCES_INDEX
  nameWithType: PackageSettings.AssetManagementConstants.K_RESOURCES_INDEX
  fullName: com.absence.variablebanks.editor.PackageSettings.AssetManagementConstants.K_RESOURCES_INDEX
  type: Field
  source:
    remote:
      path: absent-variablebanks/Assets/Plugins/absencee_/absent-variablebanks/Editor/Initial/PackageSettings.cs
      branch: development
      repo: https://github.com/b1lodHand/absent-variablebanks.git
    id: K_RESOURCES_INDEX
    path: ../absent-variablebanks/Assets/Plugins/absencee_/absent-variablebanks/Editor/Initial/PackageSettings.cs
    startLine: 16
  assemblies:
  - Assembly-CSharp-Editor-firstpass
  namespace: com.absence.variablebanks.editor
  syntax:
    content: public const int K_RESOURCES_INDEX = 0
    return:
      type: System.Int32
    content.vb: Public Const K_RESOURCES_INDEX As Integer = 0
- uid: com.absence.variablebanks.editor.PackageSettings.AssetManagementConstants.K_ADDRESSABLES_INDEX
  commentId: F:com.absence.variablebanks.editor.PackageSettings.AssetManagementConstants.K_ADDRESSABLES_INDEX
  id: K_ADDRESSABLES_INDEX
  parent: com.absence.variablebanks.editor.PackageSettings.AssetManagementConstants
  langs:
  - csharp
  - vb
  name: K_ADDRESSABLES_INDEX
  nameWithType: PackageSettings.AssetManagementConstants.K_ADDRESSABLES_INDEX
  fullName: com.absence.variablebanks.editor.PackageSettings.AssetManagementConstants.K_ADDRESSABLES_INDEX
  type: Field
  source:
    remote:
      path: absent-variablebanks/Assets/Plugins/absencee_/absent-variablebanks/Editor/Initial/PackageSettings.cs
      branch: development
      repo: https://github.com/b1lodHand/absent-variablebanks.git
    id: K_ADDRESSABLES_INDEX
    path: ../absent-variablebanks/Assets/Plugins/absencee_/absent-variablebanks/Editor/Initial/PackageSettings.cs
    startLine: 17
  assemblies:
  - Assembly-CSharp-Editor-firstpass
  namespace: com.absence.variablebanks.editor
  syntax:
    content: public const int K_ADDRESSABLES_INDEX = 1
    return:
      type: System.Int32
    content.vb: Public Const K_ADDRESSABLES_INDEX As Integer = 1
references:
- uid: com.absence.variablebanks.editor
  commentId: N:com.absence.variablebanks.editor
  href: com.html
  name: com.absence.variablebanks.editor
  nameWithType: com.absence.variablebanks.editor
  fullName: com.absence.variablebanks.editor
  spec.csharp:
  - uid: com
    name: com
    href: com.html
  - name: .
  - uid: com.absence
    name: absence
    href: com.absence.html
  - name: .
  - uid: com.absence.variablebanks
    name: variablebanks
    href: com.absence.variablebanks.html
  - name: .
  - uid: com.absence.variablebanks.editor
    name: editor
    href: com.absence.variablebanks.editor.html
  spec.vb:
  - uid: com
    name: com
    href: com.html
  - name: .
  - uid: com.absence
    name: absence
    href: com.absence.html
  - name: .
  - uid: com.absence.variablebanks
    name: variablebanks
    href: com.absence.variablebanks.html
  - name: .
  - uid: com.absence.variablebanks.editor
    name: editor
    href: com.absence.variablebanks.editor.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
